name: roast
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  google_fonts: ^6.3.0
  image_picker: ^1.2.0
  permission_handler: ^12.0.1
  auto_size_text: ^3.0.0
  share_plus: ^11.1.0
  flutter_native_splash: ^2.4.6
  flutter_image_compress: ^2.4.0
  flutter_local_notifications: ^19.4.1
  timezone: ^0.10.1
  flutter_timezone: ^4.1.1
  purchases_ui_flutter: ^9.2.1
  purchases_flutter: ^9.2.1
  http: ^1.5.0
  get_storage: ^2.1.1
  lottie: ^3.3.1
  intl: ^0.20.2
  get: ^4.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Image/
    - assets/Fire_animation.json
  fonts:
    - family: AptosNarrow
      fonts:
        - asset: assets/fonts/Aptos-Narrow.ttf
        - asset: assets/fonts/Aptos-Narrow-Bold.ttf
          weight: 700
    - family: AptosDisplay
      fonts:
        - asset: assets/fonts/Aptos-Display-Bold.ttf
          weight: 700
    - family: AptosExtraBold
      fonts:
        - asset: assets/fonts/Aptos-ExtraBold.ttf
          weight: 800
    - family: AptosSemiBold
      fonts:
        - asset: assets/fonts/Aptos-SemiBold.ttf
          weight: 600

flutter_native_splash:
  color: "#ffffff"
  image: assets/Image/appicon.png
  android_gravity: center
  ios_content_mode: center
  fullscreen: false
  android: true
  ios: true
